### ISSUE TITLE
Implement deletion of Resources

### ISSUE THREAD

**Issue by merkys** [EnjoyCpp/jsonapi-client-cpp#53]
According to JSON API specification, to delete a Resource, a `DELETE` request should be sent to `/<type>/<id>`. To implement this, a method `bool Server::delete( const std::string type, const std::string id )` should be added.

**Comment by EnjoyCpp** [comment]
@merkys added method `bool Resource::deleteResource( const std::string type, const std::string id )` instead of `bool Server::delete( const std::string type, const std::string id )`. Changed name because delete is an operator. It seems to work correctly. Also added test for testing `DELETE` request but it is not good because of fixed `ID`. If you use test two times it will fail because resource with that `ID` is already deleted.

**Comment by merkys** [comment]
> @merkys added method `bool Resource::deleteResource( const std::string type, const std::string id )` instead of `bool Server::delete( const std::string type, const std::string id )`. Changed name because delete is an operator.

Let's name it `Resource::del` then. Shorter is better, IMO.

> Also added test for testing `DELETE` request but it is not good because of fixed `ID`. If you use test two times it will fail because resource with that `ID` is already deleted.

This could be circumvented by creating issue first, and then deleting it. However, we don't have means to retrieve the ID of the created entry for now - we will fix this later.
